version: "3.1"

services:
  nginx:
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/cert:/etc/letsencrypt
    depends_on:
      - fastapi

  fastapi:
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - /home/gitlab-runner/images:/code/app/static/images
