version: "3.1"

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/cert:/etc/letsencrypt
